### ISSUE TITLE
parameters for 2K

### ISSUE THREAD

**Issue by kzoacn** [nordie92/AoE4BO#7]
I use those parameters in 2K (2560x1440) resolution. It works.

Overlay:
15 450 350 330
Supply:
42 1142 85 40
Food:
50 1220 90 40
Wood:
50 1270 90 40
Gold:
50 1320 90 40
Stone:
50 1370 90 40

BTW, it can only recongnize the first 4 digits for food,wood,gold and stone. It seems the image size is restricted, I cant enlarge it by increasing parameter width.

[Looks like this](https://imgur.com/a/l9ZJED3)

**Comment by nordie92** [comment]
Are you working on the latest version 0.9.7?
I can't reproduce this error, the width parameter works fine for me. Can you please change the values directly in the config file "config.json". You have to restart the application after file changes.

**Comment by kzoacn** [comment]
Oh yes, I just restart it. It works pretty good. Thanks.
