### ISSUE TITLE
Overlay not showing properly with Microsoft Version

### ISSUE THREAD

**Issue by pt4300** [nordie92/AoE4BO#8]
All settings are the same as the youtube guide, but only the hide and restart button is displayed inside the game. No background app is running so I think there shouldn't be any conflict between different applications. Is it possible to have an update to fix the issue with Microsoft Version?

**Comment by pt4300** [comment]
issue screenshot https://imgur.com/a/btk97je

**Comment by nordie92** [comment]
Do you try to start a match? The build order is showing up as soon the game started and resources correctly detected.

**Comment by pt4300** [comment]
Yes I have try to start match but same problem persist....

**Comment by pt4300** [comment]
Ok the problem is fixed. I have changed the screen mode from borderless to full screen and then back to bordless. The problem doesnt seems appear again afterwards.

**Comment by nordie92** [comment]
Okay, strange. For future trouble shooting you can open the settings and check if every resource is detected correctly
